#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=99
USE_PROCD=1

log() {
	logger -t "pingtest" "$@"
}

start_service()
{
	procd_open_instance
	procd_set_param command /usr/lib/custom/test_ping.sh
	procd_set_param respawn
	procd_close_instance
}
