#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=20
USE_PROCD=1

log() {
	logger -t "iframe" "$@"
}

start_service()
{
	if [ ! -d /tmp/www ]; then
		mkdir -p /tmp/www
	fi

	procd_open_instance create
	procd_set_param command /usr/lib/iframe/create.sh
	procd_set_param respawn
	procd_close_instance

	procd_open_instance status
	procd_set_param command /usr/lib/iframe/status.sh
	procd_set_param respawn
	procd_close_instance
}
